INSERT INTO `parametros` (`id`, `atributo`, `descripcion`, `estadoparametro`) VALUES
(1, 'idTipoProducto', 'Tipo de Producto', 'A'),
(2, 'IdCategoriaProducto', 'Categoria de Producto', 'A'),
(3, 'idEstadoProducto', 'Estado Peoducto', 'A'),
(4, 'idTipoIdentificacion', 'Tipo Identificacion', 'A'),
(5, 'idTipoPersona', 'Tipo de Persona', 'A'),
(6, 'IdEstadoPersona', 'Tipo Persona', 'A'),
(7, 'idEstadoFactura', 'Estado de la Factura', 'A'),
(8, 'IdEstadoUsuario', 'Estado de Usuario', 'A'),
(9, 'idRol', 'ROl del Usuario', 'A');

INSERT INTO `valorparametros` (`id`, `parametro_id`, `valor`, `orden`, `estadoValorparametro`, `idPadre`) VALUES
(5, 1, 'Hardware Computo', '01', 'A', 0),
(6, 1, 'Software de Sistemas', '02', 'A', 0),
(7, 1, 'Hardware Redes', '03', 'A', 0),
(8, 1, 'Hardware Perifericos', '04', 'A', 0),
(9, 1, 'Software Ofimatica', '05', 'A', 0),
(10, 1, 'Software verticales', '07', 'A', 0),
(11, 2, 'Portatiles', '01', 'A', 5),
(12, 2, 'Servidores', '03', 'A', 5),
(13, 2, 'PC de Escritorio', '03', 'A', 5),
(14, 2, 'Monitores', '01', 'A', 8),
(15, 2, 'Discos Duros', '02', 'A', 8),
(16, 2, 'Procesadores', '03', 'A', 8),
(17, 2, 'Memorias RAM', '05', 'A', 8),
(18, 2, 'Fuentes de Poder', '06', 'A', 8),
(19, 2, 'Mouses', '07', 'A', 8),
(20, 2, 'Mother Boards', '06', 'A', 8),
(21, 3, 'Activo', '01', 'A', NULL),
(22, 3, 'Inactivo', '03', 'A', NULL),
(23, 2, 'Multimedia ', '09', 'A', 8),
(24, 8, 'Activo', '01', 'A', NULL),
(25, 8, 'Inactivo', '02', 'A', NULL),
(26, 9, 'Administrador', '01', 'A', NULL),
(27, 9, 'Operador', '02', 'A', NULL),
(28, 9, 'Cliente', '03', 'A', NULL),
(29, 6, 'Activa', '01', 'A', NULL),
(30, 6, 'Inactiva', '02', 'A', NULL),
(31, 4, 'Cedula', '01', 'A', NULL),
(32, 4, 'Tarjeta Identidad', '02', 'A', NULL),
(33, 5, 'Empleado', '01', 'A', NULL),
(34, 5, 'Cliente', '02', 'A', NULL);
